### ISSUE TITLE
Improve testing of version 0.2

### ISSUE THREAD

**Issue by kulla** [serlo/api.serlo.org-cache-worker#10]
The current tests are quite slow and need to be much faster (see https://github.com/labs42io/clean-code-typescript#first-rules)

**Comment by hugotiburtino** [comment]
I'm also concerned with that. 

The wait function makes it almost impossible to run a unit test in less than 5 seconds.

At first place, we could use less fakekeys and pagination. 

(By the way, what do you think of the name `pace` instead of `pagination`? Would you say you can understand what it means?)

**Comment by hugotiburtino** [comment]
Leaving speed aside, what about coverage? 

For example, how could we test a key update that, after the two retries, succeeds? Maybe with a counter in a closure? Is there any simpler way?

**Comment by kulla** [comment]
Concerning speed: I would remove the test where every key is an error. I guess that's the biggest time lost due to the algorithm we have. A test where 2 keys are error keys is enough.
